@request_id = 123
@address = http://localhost:8080

POST {{address}}/users
Content-Type: application/json

{
    "username" : "blink",
    "password" : "password",
    "name" : "First User",
    "email" : "blink@email.com"
}
###
POST {{address}}/users
Content-Type: application/json

{
    "username" : "test2",
    "password" : "password",
    "name" : "Second User",
    "email" : "test2@example.com"
}
###
GET {{address}}/users
###
GET {{address}}/users/1
###
GET {{address}}/users/111
###
PUT {{address}}/users/1
Content-Type: application/json
Authorization: Bearer 7c413f6f-c7a8-42b0-a8d1-7ed0a670b2fb

{
    "name" : "First User Updated"
}
###
DELETE {{address}}/users/4
Authorization: Bearer d4b06cf7-5b32-45d8-933e-b007289ab06a

###
GET {{address}}/users/2
###
POST {{address}}/users/14/posts
Content-Type: application/json
Authorization: Bearer e63cd22f-269f-4af6-998d-0478c49e5913

{
    "Content": "Hello World"
}
###
POST {{address}}/users/1/posts
Content-Type: application/json
Authorization: Bearer e63cd22f-269f-4af6-998d-0478c49e5913

{
    "Content": "Second Post"
}
###
GET {{address}}/users/1/posts
###
GET {{address}}/users/1/posts/1
###
GET {{address}}/users/1/posts/111
###
PUT {{address}}/users/1/posts/1
Content-Type: application/json

{
    "Content": "Hello World Updated",
    "Likes": 1
}
###
GET {{address}}/users/1/posts/1
###
DELETE {{address}}/users/1/posts/2
###
GET {{address}}/users/1/posts/2
###

POST {{address}}/login
Content-Type: application/x-www-form-urlencoded

u=blink
&p=password
###
GET {{address}}/tables
X-Request-ID: {{request_id}}
Authorization: Bearer 75076717-31f0-4aa7-ba43-80567a1f4f74
###
